name: artifacts_generation

on: [push]

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install nbconvert ipykernel matplotlib pint numpy open-atmos-jupyter-utils scipy numba nbqa pylint
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex inkscape

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run nbqa pylint on notebooks
        run: |
          echo "Running nbqa pylint checks..."
          mkdir -p nbqa_reports
          FAILURES=0
          for nb in $(find . -name "*.ipynb"); do
            echo "Checking $nb..."
            nbqa pylint "$nb" > "nbqa_reports/$(basename "$nb" .ipynb)_pylint.txt" || FAILURES=$((FAILURES+1))
          done
          echo "nbqa completed with $FAILURES file(s) having issues."
          exit $FAILURES

      - name: Upload nbqa reports
        uses: actions/upload-artifact@v4
        with:
          name: nbqa-pylint-reports
          path: nbqa_reports/

      - name: Find and convert all notebooks to PDF
        run: |
          mkdir -p pdf_outputs
          for nb in $(find . -name "*.ipynb"); do
            echo "Converting $nb..."
            jupyter nbconvert --to pdf --execute "$nb" --output-dir=pdf_outputs || echo "Failed: $nb"
          done

      - name: Upload all PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-artifacts
          path: pdf_outputs/*.pdf
